// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DTO.proto
// Protobuf C++ Version: 5.29.5

#ifndef DTO_2eproto_2epb_2eh
#define DTO_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_DTO_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_DTO_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_DTO_2eproto;
namespace Protocol {
class PartyJoinRequest;
struct PartyJoinRequestDefaultTypeInternal;
extern PartyJoinRequestDefaultTypeInternal _PartyJoinRequest_default_instance_;
class PartyListEntry;
struct PartyListEntryDefaultTypeInternal;
extern PartyListEntryDefaultTypeInternal _PartyListEntry_default_instance_;
class PartyMember;
struct PartyMemberDefaultTypeInternal;
extern PartyMemberDefaultTypeInternal _PartyMember_default_instance_;
class PartySnapshot;
struct PartySnapshotDefaultTypeInternal;
extern PartySnapshotDefaultTypeInternal _PartySnapshot_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum AttackInputType : int {
  ATTACK_INPUT_LIGHT = 0,
  ATTACK_INPUT_HEAVY = 1,
  AttackInputType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AttackInputType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AttackInputType_IsValid(int value);
extern const uint32_t AttackInputType_internal_data_[];
constexpr AttackInputType AttackInputType_MIN = static_cast<AttackInputType>(0);
constexpr AttackInputType AttackInputType_MAX = static_cast<AttackInputType>(1);
constexpr int AttackInputType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
AttackInputType_descriptor();
template <typename T>
const std::string& AttackInputType_Name(T value) {
  static_assert(std::is_same<T, AttackInputType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AttackInputType_Name().");
  return AttackInputType_Name(static_cast<AttackInputType>(value));
}
template <>
inline const std::string& AttackInputType_Name(AttackInputType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AttackInputType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool AttackInputType_Parse(absl::string_view name, AttackInputType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AttackInputType>(
      AttackInputType_descriptor(), name, value);
}
enum PartyLifecycle : int {
  PARTY_LIFECYCLE_FORMING = 0,
  PARTY_LIFECYCLE_WORLD_ENTRY_PENDING = 1,
  PARTY_LIFECYCLE_IN_WORLD = 2,
  PARTY_LIFECYCLE_DISBANDED = 3,
  PartyLifecycle_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PartyLifecycle_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PartyLifecycle_IsValid(int value);
extern const uint32_t PartyLifecycle_internal_data_[];
constexpr PartyLifecycle PartyLifecycle_MIN = static_cast<PartyLifecycle>(0);
constexpr PartyLifecycle PartyLifecycle_MAX = static_cast<PartyLifecycle>(3);
constexpr int PartyLifecycle_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
PartyLifecycle_descriptor();
template <typename T>
const std::string& PartyLifecycle_Name(T value) {
  static_assert(std::is_same<T, PartyLifecycle>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PartyLifecycle_Name().");
  return PartyLifecycle_Name(static_cast<PartyLifecycle>(value));
}
template <>
inline const std::string& PartyLifecycle_Name(PartyLifecycle value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PartyLifecycle_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool PartyLifecycle_Parse(absl::string_view name, PartyLifecycle* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PartyLifecycle>(
      PartyLifecycle_descriptor(), name, value);
}
enum PartyMemberRole : int {
  PARTY_MEMBER_ROLE_LEADER = 0,
  PARTY_MEMBER_ROLE_MEMBER = 1,
  PartyMemberRole_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PartyMemberRole_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PartyMemberRole_IsValid(int value);
extern const uint32_t PartyMemberRole_internal_data_[];
constexpr PartyMemberRole PartyMemberRole_MIN = static_cast<PartyMemberRole>(0);
constexpr PartyMemberRole PartyMemberRole_MAX = static_cast<PartyMemberRole>(1);
constexpr int PartyMemberRole_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
PartyMemberRole_descriptor();
template <typename T>
const std::string& PartyMemberRole_Name(T value) {
  static_assert(std::is_same<T, PartyMemberRole>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PartyMemberRole_Name().");
  return PartyMemberRole_Name(static_cast<PartyMemberRole>(value));
}
template <>
inline const std::string& PartyMemberRole_Name(PartyMemberRole value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PartyMemberRole_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool PartyMemberRole_Parse(absl::string_view name, PartyMemberRole* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PartyMemberRole>(
      PartyMemberRole_descriptor(), name, value);
}
enum PartyMemberPresence : int {
  PARTY_MEMBER_PRESENCE_ONLINE = 0,
  PARTY_MEMBER_PRESENCE_OFFLINE = 1,
  PartyMemberPresence_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PartyMemberPresence_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PartyMemberPresence_IsValid(int value);
extern const uint32_t PartyMemberPresence_internal_data_[];
constexpr PartyMemberPresence PartyMemberPresence_MIN = static_cast<PartyMemberPresence>(0);
constexpr PartyMemberPresence PartyMemberPresence_MAX = static_cast<PartyMemberPresence>(1);
constexpr int PartyMemberPresence_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
PartyMemberPresence_descriptor();
template <typename T>
const std::string& PartyMemberPresence_Name(T value) {
  static_assert(std::is_same<T, PartyMemberPresence>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PartyMemberPresence_Name().");
  return PartyMemberPresence_Name(static_cast<PartyMemberPresence>(value));
}
template <>
inline const std::string& PartyMemberPresence_Name(PartyMemberPresence value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PartyMemberPresence_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool PartyMemberPresence_Parse(absl::string_view name, PartyMemberPresence* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PartyMemberPresence>(
      PartyMemberPresence_descriptor(), name, value);
}
enum PartyJoinRequestState : int {
  PARTY_JOIN_REQUEST_PENDING = 0,
  PARTY_JOIN_REQUEST_ACCEPTED = 1,
  PARTY_JOIN_REQUEST_REJECTED = 2,
  PARTY_JOIN_REQUEST_CANCELLED = 3,
  PARTY_JOIN_REQUEST_EXPIRED = 4,
  PartyJoinRequestState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PartyJoinRequestState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PartyJoinRequestState_IsValid(int value);
extern const uint32_t PartyJoinRequestState_internal_data_[];
constexpr PartyJoinRequestState PartyJoinRequestState_MIN = static_cast<PartyJoinRequestState>(0);
constexpr PartyJoinRequestState PartyJoinRequestState_MAX = static_cast<PartyJoinRequestState>(4);
constexpr int PartyJoinRequestState_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
PartyJoinRequestState_descriptor();
template <typename T>
const std::string& PartyJoinRequestState_Name(T value) {
  static_assert(std::is_same<T, PartyJoinRequestState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PartyJoinRequestState_Name().");
  return PartyJoinRequestState_Name(static_cast<PartyJoinRequestState>(value));
}
template <>
inline const std::string& PartyJoinRequestState_Name(PartyJoinRequestState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PartyJoinRequestState_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool PartyJoinRequestState_Parse(absl::string_view name, PartyJoinRequestState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PartyJoinRequestState>(
      PartyJoinRequestState_descriptor(), name, value);
}
enum PartyJoinRequestCloseReason : int {
  PARTY_CLOSE_NONE = 0,
  PARTY_CLOSE_ACCEPTED = 1,
  PARTY_CLOSE_REJECTED_BY_LEADER = 2,
  PARTY_CLOSE_CANCELLED_BY_REQUESTER = 3,
  PARTY_CLOSE_EXPIRED = 4,
  PARTY_CLOSE_PARTY_FULL = 5,
  PARTY_CLOSE_PARTY_ENTERED_WORLD = 6,
  PARTY_CLOSE_REQUESTER_JOINED_OTHER_PARTY = 7,
  PARTY_CLOSE_PARTY_DISBANDED = 8,
  PartyJoinRequestCloseReason_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PartyJoinRequestCloseReason_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PartyJoinRequestCloseReason_IsValid(int value);
extern const uint32_t PartyJoinRequestCloseReason_internal_data_[];
constexpr PartyJoinRequestCloseReason PartyJoinRequestCloseReason_MIN = static_cast<PartyJoinRequestCloseReason>(0);
constexpr PartyJoinRequestCloseReason PartyJoinRequestCloseReason_MAX = static_cast<PartyJoinRequestCloseReason>(8);
constexpr int PartyJoinRequestCloseReason_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor*
PartyJoinRequestCloseReason_descriptor();
template <typename T>
const std::string& PartyJoinRequestCloseReason_Name(T value) {
  static_assert(std::is_same<T, PartyJoinRequestCloseReason>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PartyJoinRequestCloseReason_Name().");
  return PartyJoinRequestCloseReason_Name(static_cast<PartyJoinRequestCloseReason>(value));
}
template <>
inline const std::string& PartyJoinRequestCloseReason_Name(PartyJoinRequestCloseReason value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PartyJoinRequestCloseReason_descriptor,
                                                 0, 8>(
      static_cast<int>(value));
}
inline bool PartyJoinRequestCloseReason_Parse(absl::string_view name, PartyJoinRequestCloseReason* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PartyJoinRequestCloseReason>(
      PartyJoinRequestCloseReason_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class PartyMember final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PartyMember) */ {
 public:
  inline PartyMember() : PartyMember(nullptr) {}
  ~PartyMember() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PartyMember* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PartyMember));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PartyMember(
      ::google::protobuf::internal::ConstantInitialized);

  inline PartyMember(const PartyMember& from) : PartyMember(nullptr, from) {}
  inline PartyMember(PartyMember&& from) noexcept
      : PartyMember(nullptr, std::move(from)) {}
  inline PartyMember& operator=(const PartyMember& from) {
    CopyFrom(from);
    return *this;
  }
  inline PartyMember& operator=(PartyMember&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PartyMember& default_instance() {
    return *internal_default_instance();
  }
  static inline const PartyMember* internal_default_instance() {
    return reinterpret_cast<const PartyMember*>(
        &_PartyMember_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PartyMember& a, PartyMember& b) { a.Swap(&b); }
  inline void Swap(PartyMember* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PartyMember* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PartyMember* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PartyMember>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PartyMember& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PartyMember& from) { PartyMember::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PartyMember* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PartyMember"; }

 protected:
  explicit PartyMember(::google::protobuf::Arena* arena);
  PartyMember(::google::protobuf::Arena* arena, const PartyMember& from);
  PartyMember(::google::protobuf::Arena* arena, PartyMember&& from) noexcept
      : PartyMember(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccountIdFieldNumber = 2,
    kSessionIdFieldNumber = 1,
    kCharacterTypeFieldNumber = 4,
    kNetIdFieldNumber = 3,
    kRoleFieldNumber = 5,
    kPresenceFieldNumber = 6,
  };
  // uint64 accountId = 2;
  void clear_accountid() ;
  ::uint64_t accountid() const;
  void set_accountid(::uint64_t value);

  private:
  ::uint64_t _internal_accountid() const;
  void _internal_set_accountid(::uint64_t value);

  public:
  // uint32 sessionId = 1;
  void clear_sessionid() ;
  ::uint32_t sessionid() const;
  void set_sessionid(::uint32_t value);

  private:
  ::uint32_t _internal_sessionid() const;
  void _internal_set_sessionid(::uint32_t value);

  public:
  // uint32 characterType = 4;
  void clear_charactertype() ;
  ::uint32_t charactertype() const;
  void set_charactertype(::uint32_t value);

  private:
  ::uint32_t _internal_charactertype() const;
  void _internal_set_charactertype(::uint32_t value);

  public:
  // uint64 netId = 3;
  void clear_netid() ;
  ::uint64_t netid() const;
  void set_netid(::uint64_t value);

  private:
  ::uint64_t _internal_netid() const;
  void _internal_set_netid(::uint64_t value);

  public:
  // .Protocol.PartyMemberRole role = 5;
  void clear_role() ;
  ::Protocol::PartyMemberRole role() const;
  void set_role(::Protocol::PartyMemberRole value);

  private:
  ::Protocol::PartyMemberRole _internal_role() const;
  void _internal_set_role(::Protocol::PartyMemberRole value);

  public:
  // .Protocol.PartyMemberPresence presence = 6;
  void clear_presence() ;
  ::Protocol::PartyMemberPresence presence() const;
  void set_presence(::Protocol::PartyMemberPresence value);

  private:
  ::Protocol::PartyMemberPresence _internal_presence() const;
  void _internal_set_presence(::Protocol::PartyMemberPresence value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PartyMember)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PartyMember& from_msg);
    ::uint64_t accountid_;
    ::uint32_t sessionid_;
    ::uint32_t charactertype_;
    ::uint64_t netid_;
    int role_;
    int presence_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DTO_2eproto;
};
// -------------------------------------------------------------------

class PartyListEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PartyListEntry) */ {
 public:
  inline PartyListEntry() : PartyListEntry(nullptr) {}
  ~PartyListEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PartyListEntry* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PartyListEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PartyListEntry(
      ::google::protobuf::internal::ConstantInitialized);

  inline PartyListEntry(const PartyListEntry& from) : PartyListEntry(nullptr, from) {}
  inline PartyListEntry(PartyListEntry&& from) noexcept
      : PartyListEntry(nullptr, std::move(from)) {}
  inline PartyListEntry& operator=(const PartyListEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline PartyListEntry& operator=(PartyListEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PartyListEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const PartyListEntry* internal_default_instance() {
    return reinterpret_cast<const PartyListEntry*>(
        &_PartyListEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PartyListEntry& a, PartyListEntry& b) { a.Swap(&b); }
  inline void Swap(PartyListEntry* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PartyListEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PartyListEntry* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PartyListEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PartyListEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PartyListEntry& from) { PartyListEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PartyListEntry* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PartyListEntry"; }

 protected:
  explicit PartyListEntry(::google::protobuf::Arena* arena);
  PartyListEntry(::google::protobuf::Arena* arena, const PartyListEntry& from);
  PartyListEntry(::google::protobuf::Arena* arena, PartyListEntry&& from) noexcept
      : PartyListEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPartyIdFieldNumber = 1,
    kLeaderSessionIdFieldNumber = 2,
    kLeaderCharacterTypeFieldNumber = 3,
    kMemberCountFieldNumber = 4,
    kCapacityFieldNumber = 5,
    kCreatedAtSecFieldNumber = 7,
    kLifecycleFieldNumber = 6,
    kJoinableFieldNumber = 8,
  };
  // uint64 partyId = 1;
  void clear_partyid() ;
  ::uint64_t partyid() const;
  void set_partyid(::uint64_t value);

  private:
  ::uint64_t _internal_partyid() const;
  void _internal_set_partyid(::uint64_t value);

  public:
  // uint32 leaderSessionId = 2;
  void clear_leadersessionid() ;
  ::uint32_t leadersessionid() const;
  void set_leadersessionid(::uint32_t value);

  private:
  ::uint32_t _internal_leadersessionid() const;
  void _internal_set_leadersessionid(::uint32_t value);

  public:
  // uint32 leaderCharacterType = 3;
  void clear_leadercharactertype() ;
  ::uint32_t leadercharactertype() const;
  void set_leadercharactertype(::uint32_t value);

  private:
  ::uint32_t _internal_leadercharactertype() const;
  void _internal_set_leadercharactertype(::uint32_t value);

  public:
  // uint32 memberCount = 4;
  void clear_membercount() ;
  ::uint32_t membercount() const;
  void set_membercount(::uint32_t value);

  private:
  ::uint32_t _internal_membercount() const;
  void _internal_set_membercount(::uint32_t value);

  public:
  // uint32 capacity = 5;
  void clear_capacity() ;
  ::uint32_t capacity() const;
  void set_capacity(::uint32_t value);

  private:
  ::uint32_t _internal_capacity() const;
  void _internal_set_capacity(::uint32_t value);

  public:
  // double createdAtSec = 7;
  void clear_createdatsec() ;
  double createdatsec() const;
  void set_createdatsec(double value);

  private:
  double _internal_createdatsec() const;
  void _internal_set_createdatsec(double value);

  public:
  // .Protocol.PartyLifecycle lifecycle = 6;
  void clear_lifecycle() ;
  ::Protocol::PartyLifecycle lifecycle() const;
  void set_lifecycle(::Protocol::PartyLifecycle value);

  private:
  ::Protocol::PartyLifecycle _internal_lifecycle() const;
  void _internal_set_lifecycle(::Protocol::PartyLifecycle value);

  public:
  // bool joinable = 8;
  void clear_joinable() ;
  bool joinable() const;
  void set_joinable(bool value);

  private:
  bool _internal_joinable() const;
  void _internal_set_joinable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PartyListEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PartyListEntry& from_msg);
    ::uint64_t partyid_;
    ::uint32_t leadersessionid_;
    ::uint32_t leadercharactertype_;
    ::uint32_t membercount_;
    ::uint32_t capacity_;
    double createdatsec_;
    int lifecycle_;
    bool joinable_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DTO_2eproto;
};
// -------------------------------------------------------------------

class PartyJoinRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PartyJoinRequest) */ {
 public:
  inline PartyJoinRequest() : PartyJoinRequest(nullptr) {}
  ~PartyJoinRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PartyJoinRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PartyJoinRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PartyJoinRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline PartyJoinRequest(const PartyJoinRequest& from) : PartyJoinRequest(nullptr, from) {}
  inline PartyJoinRequest(PartyJoinRequest&& from) noexcept
      : PartyJoinRequest(nullptr, std::move(from)) {}
  inline PartyJoinRequest& operator=(const PartyJoinRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PartyJoinRequest& operator=(PartyJoinRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PartyJoinRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PartyJoinRequest* internal_default_instance() {
    return reinterpret_cast<const PartyJoinRequest*>(
        &_PartyJoinRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PartyJoinRequest& a, PartyJoinRequest& b) { a.Swap(&b); }
  inline void Swap(PartyJoinRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PartyJoinRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PartyJoinRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PartyJoinRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PartyJoinRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PartyJoinRequest& from) { PartyJoinRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PartyJoinRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PartyJoinRequest"; }

 protected:
  explicit PartyJoinRequest(::google::protobuf::Arena* arena);
  PartyJoinRequest(::google::protobuf::Arena* arena, const PartyJoinRequest& from);
  PartyJoinRequest(::google::protobuf::Arena* arena, PartyJoinRequest&& from) noexcept
      : PartyJoinRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJoinRequestIdFieldNumber = 1,
    kPartyIdFieldNumber = 2,
    kRequesterAccountIdFieldNumber = 4,
    kRequesterSessionIdFieldNumber = 3,
    kStateFieldNumber = 5,
    kCreatedAtSecFieldNumber = 7,
    kExpiresAtSecFieldNumber = 8,
    kClosedAtSecFieldNumber = 9,
    kCloseReasonFieldNumber = 6,
  };
  // uint64 joinRequestId = 1;
  void clear_joinrequestid() ;
  ::uint64_t joinrequestid() const;
  void set_joinrequestid(::uint64_t value);

  private:
  ::uint64_t _internal_joinrequestid() const;
  void _internal_set_joinrequestid(::uint64_t value);

  public:
  // uint64 partyId = 2;
  void clear_partyid() ;
  ::uint64_t partyid() const;
  void set_partyid(::uint64_t value);

  private:
  ::uint64_t _internal_partyid() const;
  void _internal_set_partyid(::uint64_t value);

  public:
  // uint64 requesterAccountId = 4;
  void clear_requesteraccountid() ;
  ::uint64_t requesteraccountid() const;
  void set_requesteraccountid(::uint64_t value);

  private:
  ::uint64_t _internal_requesteraccountid() const;
  void _internal_set_requesteraccountid(::uint64_t value);

  public:
  // uint32 requesterSessionId = 3;
  void clear_requestersessionid() ;
  ::uint32_t requestersessionid() const;
  void set_requestersessionid(::uint32_t value);

  private:
  ::uint32_t _internal_requestersessionid() const;
  void _internal_set_requestersessionid(::uint32_t value);

  public:
  // .Protocol.PartyJoinRequestState state = 5;
  void clear_state() ;
  ::Protocol::PartyJoinRequestState state() const;
  void set_state(::Protocol::PartyJoinRequestState value);

  private:
  ::Protocol::PartyJoinRequestState _internal_state() const;
  void _internal_set_state(::Protocol::PartyJoinRequestState value);

  public:
  // double createdAtSec = 7;
  void clear_createdatsec() ;
  double createdatsec() const;
  void set_createdatsec(double value);

  private:
  double _internal_createdatsec() const;
  void _internal_set_createdatsec(double value);

  public:
  // double expiresAtSec = 8;
  void clear_expiresatsec() ;
  double expiresatsec() const;
  void set_expiresatsec(double value);

  private:
  double _internal_expiresatsec() const;
  void _internal_set_expiresatsec(double value);

  public:
  // double closedAtSec = 9;
  void clear_closedatsec() ;
  double closedatsec() const;
  void set_closedatsec(double value);

  private:
  double _internal_closedatsec() const;
  void _internal_set_closedatsec(double value);

  public:
  // .Protocol.PartyJoinRequestCloseReason closeReason = 6;
  void clear_closereason() ;
  ::Protocol::PartyJoinRequestCloseReason closereason() const;
  void set_closereason(::Protocol::PartyJoinRequestCloseReason value);

  private:
  ::Protocol::PartyJoinRequestCloseReason _internal_closereason() const;
  void _internal_set_closereason(::Protocol::PartyJoinRequestCloseReason value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PartyJoinRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PartyJoinRequest& from_msg);
    ::uint64_t joinrequestid_;
    ::uint64_t partyid_;
    ::uint64_t requesteraccountid_;
    ::uint32_t requestersessionid_;
    int state_;
    double createdatsec_;
    double expiresatsec_;
    double closedatsec_;
    int closereason_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DTO_2eproto;
};
// -------------------------------------------------------------------

class PartySnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PartySnapshot) */ {
 public:
  inline PartySnapshot() : PartySnapshot(nullptr) {}
  ~PartySnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PartySnapshot* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PartySnapshot));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PartySnapshot(
      ::google::protobuf::internal::ConstantInitialized);

  inline PartySnapshot(const PartySnapshot& from) : PartySnapshot(nullptr, from) {}
  inline PartySnapshot(PartySnapshot&& from) noexcept
      : PartySnapshot(nullptr, std::move(from)) {}
  inline PartySnapshot& operator=(const PartySnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline PartySnapshot& operator=(PartySnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PartySnapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const PartySnapshot* internal_default_instance() {
    return reinterpret_cast<const PartySnapshot*>(
        &_PartySnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PartySnapshot& a, PartySnapshot& b) { a.Swap(&b); }
  inline void Swap(PartySnapshot* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PartySnapshot* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PartySnapshot* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PartySnapshot>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PartySnapshot& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PartySnapshot& from) { PartySnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PartySnapshot* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PartySnapshot"; }

 protected:
  explicit PartySnapshot(::google::protobuf::Arena* arena);
  PartySnapshot(::google::protobuf::Arena* arena, const PartySnapshot& from);
  PartySnapshot(::google::protobuf::Arena* arena, PartySnapshot&& from) noexcept
      : PartySnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMembersFieldNumber = 4,
    kJoinRequestsFieldNumber = 5,
    kPartyIdFieldNumber = 1,
    kLifecycleFieldNumber = 2,
    kLeaderSessionIdFieldNumber = 3,
    kCreatedAtSecFieldNumber = 6,
    kJoinableFieldNumber = 7,
  };
  // repeated .Protocol.PartyMember members = 4;
  int members_size() const;
  private:
  int _internal_members_size() const;

  public:
  void clear_members() ;
  ::Protocol::PartyMember* mutable_members(int index);
  ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>* mutable_members();

  private:
  const ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>& _internal_members() const;
  ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>* _internal_mutable_members();
  public:
  const ::Protocol::PartyMember& members(int index) const;
  ::Protocol::PartyMember* add_members();
  const ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>& members() const;
  // repeated .Protocol.PartyJoinRequest joinRequests = 5;
  int joinrequests_size() const;
  private:
  int _internal_joinrequests_size() const;

  public:
  void clear_joinrequests() ;
  ::Protocol::PartyJoinRequest* mutable_joinrequests(int index);
  ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>* mutable_joinrequests();

  private:
  const ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>& _internal_joinrequests() const;
  ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>* _internal_mutable_joinrequests();
  public:
  const ::Protocol::PartyJoinRequest& joinrequests(int index) const;
  ::Protocol::PartyJoinRequest* add_joinrequests();
  const ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>& joinrequests() const;
  // uint64 partyId = 1;
  void clear_partyid() ;
  ::uint64_t partyid() const;
  void set_partyid(::uint64_t value);

  private:
  ::uint64_t _internal_partyid() const;
  void _internal_set_partyid(::uint64_t value);

  public:
  // .Protocol.PartyLifecycle lifecycle = 2;
  void clear_lifecycle() ;
  ::Protocol::PartyLifecycle lifecycle() const;
  void set_lifecycle(::Protocol::PartyLifecycle value);

  private:
  ::Protocol::PartyLifecycle _internal_lifecycle() const;
  void _internal_set_lifecycle(::Protocol::PartyLifecycle value);

  public:
  // uint32 leaderSessionId = 3;
  void clear_leadersessionid() ;
  ::uint32_t leadersessionid() const;
  void set_leadersessionid(::uint32_t value);

  private:
  ::uint32_t _internal_leadersessionid() const;
  void _internal_set_leadersessionid(::uint32_t value);

  public:
  // double createdAtSec = 6;
  void clear_createdatsec() ;
  double createdatsec() const;
  void set_createdatsec(double value);

  private:
  double _internal_createdatsec() const;
  void _internal_set_createdatsec(double value);

  public:
  // bool joinable = 7;
  void clear_joinable() ;
  bool joinable() const;
  void set_joinable(bool value);

  private:
  bool _internal_joinable() const;
  void _internal_set_joinable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PartySnapshot)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PartySnapshot& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Protocol::PartyMember > members_;
    ::google::protobuf::RepeatedPtrField< ::Protocol::PartyJoinRequest > joinrequests_;
    ::uint64_t partyid_;
    int lifecycle_;
    ::uint32_t leadersessionid_;
    double createdatsec_;
    bool joinable_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DTO_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PartyMember

// uint32 sessionId = 1;
inline void PartyMember::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_ = 0u;
}
inline ::uint32_t PartyMember::sessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyMember.sessionId)
  return _internal_sessionid();
}
inline void PartyMember::set_sessionid(::uint32_t value) {
  _internal_set_sessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyMember.sessionId)
}
inline ::uint32_t PartyMember::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_;
}
inline void PartyMember::_internal_set_sessionid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_ = value;
}

// uint64 accountId = 2;
inline void PartyMember::clear_accountid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accountid_ = ::uint64_t{0u};
}
inline ::uint64_t PartyMember::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyMember.accountId)
  return _internal_accountid();
}
inline void PartyMember::set_accountid(::uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyMember.accountId)
}
inline ::uint64_t PartyMember::_internal_accountid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accountid_;
}
inline void PartyMember::_internal_set_accountid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accountid_ = value;
}

// uint64 netId = 3;
inline void PartyMember::clear_netid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.netid_ = ::uint64_t{0u};
}
inline ::uint64_t PartyMember::netid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyMember.netId)
  return _internal_netid();
}
inline void PartyMember::set_netid(::uint64_t value) {
  _internal_set_netid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyMember.netId)
}
inline ::uint64_t PartyMember::_internal_netid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.netid_;
}
inline void PartyMember::_internal_set_netid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.netid_ = value;
}

// uint32 characterType = 4;
inline void PartyMember::clear_charactertype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.charactertype_ = 0u;
}
inline ::uint32_t PartyMember::charactertype() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyMember.characterType)
  return _internal_charactertype();
}
inline void PartyMember::set_charactertype(::uint32_t value) {
  _internal_set_charactertype(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyMember.characterType)
}
inline ::uint32_t PartyMember::_internal_charactertype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.charactertype_;
}
inline void PartyMember::_internal_set_charactertype(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.charactertype_ = value;
}

// .Protocol.PartyMemberRole role = 5;
inline void PartyMember::clear_role() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.role_ = 0;
}
inline ::Protocol::PartyMemberRole PartyMember::role() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyMember.role)
  return _internal_role();
}
inline void PartyMember::set_role(::Protocol::PartyMemberRole value) {
  _internal_set_role(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyMember.role)
}
inline ::Protocol::PartyMemberRole PartyMember::_internal_role() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PartyMemberRole>(_impl_.role_);
}
inline void PartyMember::_internal_set_role(::Protocol::PartyMemberRole value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.role_ = value;
}

// .Protocol.PartyMemberPresence presence = 6;
inline void PartyMember::clear_presence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.presence_ = 0;
}
inline ::Protocol::PartyMemberPresence PartyMember::presence() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyMember.presence)
  return _internal_presence();
}
inline void PartyMember::set_presence(::Protocol::PartyMemberPresence value) {
  _internal_set_presence(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyMember.presence)
}
inline ::Protocol::PartyMemberPresence PartyMember::_internal_presence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PartyMemberPresence>(_impl_.presence_);
}
inline void PartyMember::_internal_set_presence(::Protocol::PartyMemberPresence value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.presence_ = value;
}

// -------------------------------------------------------------------

// PartyJoinRequest

// uint64 joinRequestId = 1;
inline void PartyJoinRequest::clear_joinrequestid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinrequestid_ = ::uint64_t{0u};
}
inline ::uint64_t PartyJoinRequest::joinrequestid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.joinRequestId)
  return _internal_joinrequestid();
}
inline void PartyJoinRequest::set_joinrequestid(::uint64_t value) {
  _internal_set_joinrequestid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.joinRequestId)
}
inline ::uint64_t PartyJoinRequest::_internal_joinrequestid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.joinrequestid_;
}
inline void PartyJoinRequest::_internal_set_joinrequestid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinrequestid_ = value;
}

// uint64 partyId = 2;
inline void PartyJoinRequest::clear_partyid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partyid_ = ::uint64_t{0u};
}
inline ::uint64_t PartyJoinRequest::partyid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.partyId)
  return _internal_partyid();
}
inline void PartyJoinRequest::set_partyid(::uint64_t value) {
  _internal_set_partyid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.partyId)
}
inline ::uint64_t PartyJoinRequest::_internal_partyid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.partyid_;
}
inline void PartyJoinRequest::_internal_set_partyid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partyid_ = value;
}

// uint32 requesterSessionId = 3;
inline void PartyJoinRequest::clear_requestersessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requestersessionid_ = 0u;
}
inline ::uint32_t PartyJoinRequest::requestersessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.requesterSessionId)
  return _internal_requestersessionid();
}
inline void PartyJoinRequest::set_requestersessionid(::uint32_t value) {
  _internal_set_requestersessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.requesterSessionId)
}
inline ::uint32_t PartyJoinRequest::_internal_requestersessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.requestersessionid_;
}
inline void PartyJoinRequest::_internal_set_requestersessionid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requestersessionid_ = value;
}

// uint64 requesterAccountId = 4;
inline void PartyJoinRequest::clear_requesteraccountid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requesteraccountid_ = ::uint64_t{0u};
}
inline ::uint64_t PartyJoinRequest::requesteraccountid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.requesterAccountId)
  return _internal_requesteraccountid();
}
inline void PartyJoinRequest::set_requesteraccountid(::uint64_t value) {
  _internal_set_requesteraccountid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.requesterAccountId)
}
inline ::uint64_t PartyJoinRequest::_internal_requesteraccountid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.requesteraccountid_;
}
inline void PartyJoinRequest::_internal_set_requesteraccountid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requesteraccountid_ = value;
}

// .Protocol.PartyJoinRequestState state = 5;
inline void PartyJoinRequest::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0;
}
inline ::Protocol::PartyJoinRequestState PartyJoinRequest::state() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.state)
  return _internal_state();
}
inline void PartyJoinRequest::set_state(::Protocol::PartyJoinRequestState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.state)
}
inline ::Protocol::PartyJoinRequestState PartyJoinRequest::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PartyJoinRequestState>(_impl_.state_);
}
inline void PartyJoinRequest::_internal_set_state(::Protocol::PartyJoinRequestState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// .Protocol.PartyJoinRequestCloseReason closeReason = 6;
inline void PartyJoinRequest::clear_closereason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.closereason_ = 0;
}
inline ::Protocol::PartyJoinRequestCloseReason PartyJoinRequest::closereason() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.closeReason)
  return _internal_closereason();
}
inline void PartyJoinRequest::set_closereason(::Protocol::PartyJoinRequestCloseReason value) {
  _internal_set_closereason(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.closeReason)
}
inline ::Protocol::PartyJoinRequestCloseReason PartyJoinRequest::_internal_closereason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PartyJoinRequestCloseReason>(_impl_.closereason_);
}
inline void PartyJoinRequest::_internal_set_closereason(::Protocol::PartyJoinRequestCloseReason value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.closereason_ = value;
}

// double createdAtSec = 7;
inline void PartyJoinRequest::clear_createdatsec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.createdatsec_ = 0;
}
inline double PartyJoinRequest::createdatsec() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.createdAtSec)
  return _internal_createdatsec();
}
inline void PartyJoinRequest::set_createdatsec(double value) {
  _internal_set_createdatsec(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.createdAtSec)
}
inline double PartyJoinRequest::_internal_createdatsec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.createdatsec_;
}
inline void PartyJoinRequest::_internal_set_createdatsec(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.createdatsec_ = value;
}

// double expiresAtSec = 8;
inline void PartyJoinRequest::clear_expiresatsec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expiresatsec_ = 0;
}
inline double PartyJoinRequest::expiresatsec() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.expiresAtSec)
  return _internal_expiresatsec();
}
inline void PartyJoinRequest::set_expiresatsec(double value) {
  _internal_set_expiresatsec(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.expiresAtSec)
}
inline double PartyJoinRequest::_internal_expiresatsec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expiresatsec_;
}
inline void PartyJoinRequest::_internal_set_expiresatsec(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expiresatsec_ = value;
}

// double closedAtSec = 9;
inline void PartyJoinRequest::clear_closedatsec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.closedatsec_ = 0;
}
inline double PartyJoinRequest::closedatsec() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyJoinRequest.closedAtSec)
  return _internal_closedatsec();
}
inline void PartyJoinRequest::set_closedatsec(double value) {
  _internal_set_closedatsec(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyJoinRequest.closedAtSec)
}
inline double PartyJoinRequest::_internal_closedatsec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.closedatsec_;
}
inline void PartyJoinRequest::_internal_set_closedatsec(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.closedatsec_ = value;
}

// -------------------------------------------------------------------

// PartySnapshot

// uint64 partyId = 1;
inline void PartySnapshot::clear_partyid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partyid_ = ::uint64_t{0u};
}
inline ::uint64_t PartySnapshot::partyid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.partyId)
  return _internal_partyid();
}
inline void PartySnapshot::set_partyid(::uint64_t value) {
  _internal_set_partyid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartySnapshot.partyId)
}
inline ::uint64_t PartySnapshot::_internal_partyid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.partyid_;
}
inline void PartySnapshot::_internal_set_partyid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partyid_ = value;
}

// .Protocol.PartyLifecycle lifecycle = 2;
inline void PartySnapshot::clear_lifecycle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lifecycle_ = 0;
}
inline ::Protocol::PartyLifecycle PartySnapshot::lifecycle() const {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.lifecycle)
  return _internal_lifecycle();
}
inline void PartySnapshot::set_lifecycle(::Protocol::PartyLifecycle value) {
  _internal_set_lifecycle(value);
  // @@protoc_insertion_point(field_set:Protocol.PartySnapshot.lifecycle)
}
inline ::Protocol::PartyLifecycle PartySnapshot::_internal_lifecycle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PartyLifecycle>(_impl_.lifecycle_);
}
inline void PartySnapshot::_internal_set_lifecycle(::Protocol::PartyLifecycle value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lifecycle_ = value;
}

// uint32 leaderSessionId = 3;
inline void PartySnapshot::clear_leadersessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadersessionid_ = 0u;
}
inline ::uint32_t PartySnapshot::leadersessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.leaderSessionId)
  return _internal_leadersessionid();
}
inline void PartySnapshot::set_leadersessionid(::uint32_t value) {
  _internal_set_leadersessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartySnapshot.leaderSessionId)
}
inline ::uint32_t PartySnapshot::_internal_leadersessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leadersessionid_;
}
inline void PartySnapshot::_internal_set_leadersessionid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadersessionid_ = value;
}

// repeated .Protocol.PartyMember members = 4;
inline int PartySnapshot::_internal_members_size() const {
  return _internal_members().size();
}
inline int PartySnapshot::members_size() const {
  return _internal_members_size();
}
inline void PartySnapshot::clear_members() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.members_.Clear();
}
inline ::Protocol::PartyMember* PartySnapshot::mutable_members(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Protocol.PartySnapshot.members)
  return _internal_mutable_members()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>* PartySnapshot::mutable_members()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Protocol.PartySnapshot.members)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_members();
}
inline const ::Protocol::PartyMember& PartySnapshot::members(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.members)
  return _internal_members().Get(index);
}
inline ::Protocol::PartyMember* PartySnapshot::add_members() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Protocol::PartyMember* _add = _internal_mutable_members()->Add();
  // @@protoc_insertion_point(field_add:Protocol.PartySnapshot.members)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>& PartySnapshot::members() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Protocol.PartySnapshot.members)
  return _internal_members();
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>&
PartySnapshot::_internal_members() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.members_;
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PartyMember>*
PartySnapshot::_internal_mutable_members() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.members_;
}

// repeated .Protocol.PartyJoinRequest joinRequests = 5;
inline int PartySnapshot::_internal_joinrequests_size() const {
  return _internal_joinrequests().size();
}
inline int PartySnapshot::joinrequests_size() const {
  return _internal_joinrequests_size();
}
inline void PartySnapshot::clear_joinrequests() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinrequests_.Clear();
}
inline ::Protocol::PartyJoinRequest* PartySnapshot::mutable_joinrequests(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Protocol.PartySnapshot.joinRequests)
  return _internal_mutable_joinrequests()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>* PartySnapshot::mutable_joinrequests()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Protocol.PartySnapshot.joinRequests)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_joinrequests();
}
inline const ::Protocol::PartyJoinRequest& PartySnapshot::joinrequests(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.joinRequests)
  return _internal_joinrequests().Get(index);
}
inline ::Protocol::PartyJoinRequest* PartySnapshot::add_joinrequests() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Protocol::PartyJoinRequest* _add = _internal_mutable_joinrequests()->Add();
  // @@protoc_insertion_point(field_add:Protocol.PartySnapshot.joinRequests)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>& PartySnapshot::joinrequests() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Protocol.PartySnapshot.joinRequests)
  return _internal_joinrequests();
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>&
PartySnapshot::_internal_joinrequests() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.joinrequests_;
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PartyJoinRequest>*
PartySnapshot::_internal_mutable_joinrequests() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.joinrequests_;
}

// double createdAtSec = 6;
inline void PartySnapshot::clear_createdatsec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.createdatsec_ = 0;
}
inline double PartySnapshot::createdatsec() const {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.createdAtSec)
  return _internal_createdatsec();
}
inline void PartySnapshot::set_createdatsec(double value) {
  _internal_set_createdatsec(value);
  // @@protoc_insertion_point(field_set:Protocol.PartySnapshot.createdAtSec)
}
inline double PartySnapshot::_internal_createdatsec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.createdatsec_;
}
inline void PartySnapshot::_internal_set_createdatsec(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.createdatsec_ = value;
}

// bool joinable = 7;
inline void PartySnapshot::clear_joinable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinable_ = false;
}
inline bool PartySnapshot::joinable() const {
  // @@protoc_insertion_point(field_get:Protocol.PartySnapshot.joinable)
  return _internal_joinable();
}
inline void PartySnapshot::set_joinable(bool value) {
  _internal_set_joinable(value);
  // @@protoc_insertion_point(field_set:Protocol.PartySnapshot.joinable)
}
inline bool PartySnapshot::_internal_joinable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.joinable_;
}
inline void PartySnapshot::_internal_set_joinable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinable_ = value;
}

// -------------------------------------------------------------------

// PartyListEntry

// uint64 partyId = 1;
inline void PartyListEntry::clear_partyid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partyid_ = ::uint64_t{0u};
}
inline ::uint64_t PartyListEntry::partyid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.partyId)
  return _internal_partyid();
}
inline void PartyListEntry::set_partyid(::uint64_t value) {
  _internal_set_partyid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.partyId)
}
inline ::uint64_t PartyListEntry::_internal_partyid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.partyid_;
}
inline void PartyListEntry::_internal_set_partyid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partyid_ = value;
}

// uint32 leaderSessionId = 2;
inline void PartyListEntry::clear_leadersessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadersessionid_ = 0u;
}
inline ::uint32_t PartyListEntry::leadersessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.leaderSessionId)
  return _internal_leadersessionid();
}
inline void PartyListEntry::set_leadersessionid(::uint32_t value) {
  _internal_set_leadersessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.leaderSessionId)
}
inline ::uint32_t PartyListEntry::_internal_leadersessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leadersessionid_;
}
inline void PartyListEntry::_internal_set_leadersessionid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadersessionid_ = value;
}

// uint32 leaderCharacterType = 3;
inline void PartyListEntry::clear_leadercharactertype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadercharactertype_ = 0u;
}
inline ::uint32_t PartyListEntry::leadercharactertype() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.leaderCharacterType)
  return _internal_leadercharactertype();
}
inline void PartyListEntry::set_leadercharactertype(::uint32_t value) {
  _internal_set_leadercharactertype(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.leaderCharacterType)
}
inline ::uint32_t PartyListEntry::_internal_leadercharactertype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leadercharactertype_;
}
inline void PartyListEntry::_internal_set_leadercharactertype(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadercharactertype_ = value;
}

// uint32 memberCount = 4;
inline void PartyListEntry::clear_membercount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.membercount_ = 0u;
}
inline ::uint32_t PartyListEntry::membercount() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.memberCount)
  return _internal_membercount();
}
inline void PartyListEntry::set_membercount(::uint32_t value) {
  _internal_set_membercount(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.memberCount)
}
inline ::uint32_t PartyListEntry::_internal_membercount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.membercount_;
}
inline void PartyListEntry::_internal_set_membercount(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.membercount_ = value;
}

// uint32 capacity = 5;
inline void PartyListEntry::clear_capacity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.capacity_ = 0u;
}
inline ::uint32_t PartyListEntry::capacity() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.capacity)
  return _internal_capacity();
}
inline void PartyListEntry::set_capacity(::uint32_t value) {
  _internal_set_capacity(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.capacity)
}
inline ::uint32_t PartyListEntry::_internal_capacity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.capacity_;
}
inline void PartyListEntry::_internal_set_capacity(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.capacity_ = value;
}

// .Protocol.PartyLifecycle lifecycle = 6;
inline void PartyListEntry::clear_lifecycle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lifecycle_ = 0;
}
inline ::Protocol::PartyLifecycle PartyListEntry::lifecycle() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.lifecycle)
  return _internal_lifecycle();
}
inline void PartyListEntry::set_lifecycle(::Protocol::PartyLifecycle value) {
  _internal_set_lifecycle(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.lifecycle)
}
inline ::Protocol::PartyLifecycle PartyListEntry::_internal_lifecycle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PartyLifecycle>(_impl_.lifecycle_);
}
inline void PartyListEntry::_internal_set_lifecycle(::Protocol::PartyLifecycle value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lifecycle_ = value;
}

// double createdAtSec = 7;
inline void PartyListEntry::clear_createdatsec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.createdatsec_ = 0;
}
inline double PartyListEntry::createdatsec() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.createdAtSec)
  return _internal_createdatsec();
}
inline void PartyListEntry::set_createdatsec(double value) {
  _internal_set_createdatsec(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.createdAtSec)
}
inline double PartyListEntry::_internal_createdatsec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.createdatsec_;
}
inline void PartyListEntry::_internal_set_createdatsec(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.createdatsec_ = value;
}

// bool joinable = 8;
inline void PartyListEntry::clear_joinable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinable_ = false;
}
inline bool PartyListEntry::joinable() const {
  // @@protoc_insertion_point(field_get:Protocol.PartyListEntry.joinable)
  return _internal_joinable();
}
inline void PartyListEntry::set_joinable(bool value) {
  _internal_set_joinable(value);
  // @@protoc_insertion_point(field_set:Protocol.PartyListEntry.joinable)
}
inline bool PartyListEntry::_internal_joinable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.joinable_;
}
inline void PartyListEntry::_internal_set_joinable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.joinable_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::AttackInputType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::AttackInputType>() {
  return ::Protocol::AttackInputType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::PartyLifecycle> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PartyLifecycle>() {
  return ::Protocol::PartyLifecycle_descriptor();
}
template <>
struct is_proto_enum<::Protocol::PartyMemberRole> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PartyMemberRole>() {
  return ::Protocol::PartyMemberRole_descriptor();
}
template <>
struct is_proto_enum<::Protocol::PartyMemberPresence> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PartyMemberPresence>() {
  return ::Protocol::PartyMemberPresence_descriptor();
}
template <>
struct is_proto_enum<::Protocol::PartyJoinRequestState> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PartyJoinRequestState>() {
  return ::Protocol::PartyJoinRequestState_descriptor();
}
template <>
struct is_proto_enum<::Protocol::PartyJoinRequestCloseReason> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PartyJoinRequestCloseReason>() {
  return ::Protocol::PartyJoinRequestCloseReason_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // DTO_2eproto_2epb_2eh
