syntax = "proto3";
package Protocol;

/* ------------------------------ [ Client -> Server ]  ------------------------------ */

message CS_LOGIN_PACKET
{
}

message CS_MOVE_PACKET
{
	int32 inputX = 1;
	int32 inputZ = 2;
	float yaw = 3;
	bool isRun = 4;
}

message CS_ATTACK_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_DODGE_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_GUARD_PACKET
{
	bool input = 1;
}

message CS_PARRY_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

/* ------------------------------ [ Server -> Client ]  ------------------------------ */

message SC_LOGIN_PACKET
{
	uint64 netid = 1;
}

message SC_ADD_PACKET
{
	uint64 netid = 1;
	uint32 typeid = 2;
	float x = 3;
	float y = 4;
	float z = 5;
	float yaw = 6;
}

message SC_MOVE_PACKET
{
	uint64 netid = 1;
	float x = 2;
	float y = 3;
	float z = 4;
	float yaw = 5;
}

message SC_REMOVE_PACKET
{
	uint64 netid = 1;
}

message SC_ANIMATION_TRANSITION_PACKET
{
	uint64 netid = 1;
    int32 currAnim = 2;
}

message SC_STAT_CHANGE_PACKET
{
	uint64 netid = 1;
	uint32 hp = 2;
	uint32 stamina = 3;
}

message SC_REPLICATION_FRAME_PACKET
{
	uint32 frameSeq = 1;
	uint32 serverTick = 2;

	repeated SC_ADD_PACKET spawns = 3;
	repeated SC_REMOVE_PACKET despawns = 4;

	repeated SC_MOVE_PACKET moves = 5;
	repeated SC_ANIMATION_TRANSITION_PACKET anims = 6;
}