syntax = "proto3";
package Protocol;

/* ------------------------------ [ Client -> Server ]  ------------------------------ */

message CS_LOGIN_PACKET
{
}

message CS_MOVE_PACKET
{
	int32 inputX = 1;
	int32 inputZ = 2;
	float yaw = 3;
}

message CS_ATTACK_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_DODGE_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_GUARD_PACKET
{
	bool input = 1;
}

message CS_PARRY_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

/* ------------------------------ [ Server -> Client ]  ------------------------------ */

message SC_LOGIN_PACKET
{
	int32 sessionId = 1;
}

message SC_ADD_PACKET
{
	int32 sessionId = 1;
	float x = 2;
	float y = 3;
	float z = 4;
	float yaw = 5;
}

message SC_MOVE_PACKET
{
	int32 sessionId = 1;
	float x = 2;
	float y = 3;
	float z = 4;
	float yaw = 5;
}

message SC_REMOVE_PACKET
{
	int32 ssessionId = 1;
}

message SC_ANIMATION_TRANSITION_PACKET
{
    int32 prevAnim = 1;
    int32 currAnim = 2;
}