syntax = "proto3";
package Protocol;

import "DTO.proto";

/* ------------------------------ [ Client -> Server ]  ------------------------------ */

message CS_TIME_SYNC_PACKET
{
	uint32 probeSeq = 1;
	uint32 echoedServerSendTimeMs = 2;
}

message CS_LOGIN_PACKET
{
	string loginId = 1;
	string password = 2;
	string clientVersion = 3;
}

message CS_CHARACTER_SELECT_PACKET
{
	uint32 characterId = 1;
}

message CS_MOVE_PACKET
{
	int32 inputX = 1;
	int32 inputZ = 2;
	float yaw = 3;
	bool isRun = 4;
}

message CS_ATTACK_PACKET
{
	float dirX = 1;
	float dirZ = 2;

	uint32 clientAnimId = 3;
	float clientNormalizedTime = 4;
	uint32 clientAbilityInstanceId = 5;

	AttackInputType attackInputType = 6;
}

message CS_DODGE_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_GUARD_PACKET
{
	bool input = 1;
}

message CS_PARRY_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_USE_ITEM_PACKET
{
	float dirX = 1;
	float dirZ = 2;
}

message CS_WORLD_TRANSITION_REQUEST_PACKET
{
	uint32 requestId = 1;
}

message CS_WORLD_TRANSITION_READY_PACKET
{
	uint64 transferId = 1;
}

message CS_PARTY_UI_OPENED_PACKET
{
	uint32 clientRequestId = 1;
}

message CS_PARTY_UI_CLOSED_PACKET
{
	uint32 clientRequestId = 1;
}

message CS_PARTY_LIST_REFRESH_PACKET
{
	uint32 clientRequestId = 1;
}

message CS_PARTY_CREATE_PACKET
{
	uint32 clientRequestId = 1;
}

message CS_PARTY_JOIN_REQUEST_PACKET
{
	uint32 clientRequestId = 1;
	uint64 partyId = 2;
}

message CS_PARTY_JOIN_ACCEPT_PACKET
{
	uint32 clientRequestId = 1;
	uint64 joinRequestId = 2;
}

message CS_PARTY_JOIN_REJECT_PACKET
{
	uint32 clientRequestId = 1;
	uint64 joinRequestId = 2;
}

message CS_RESPAWN_REQUEST_PACKET
{
	uint32 clientRequestId = 1;
}

message CS_STAT_UI_OPENED_PACKET
{
	uint32 clientRequestId = 1;
}

message CS_TITLE_EQUIP_REQUEST_PACKET
{
	uint32 clientRequestId = 1;
	uint32 titleId = 2;
}

message CS_FINAL_CLEAR_CHOICE_SUBMIT_PACKET
{
	uint64 voteId = 1;
	bool choosePvp = 2;
}

message CS_FINAL_ENDING_CINEMATIC_DONE_PACKET
{
	FinalEndingCinematicContext context = 1;
}

message CS_BEACON_CINEMATIC_START_REQUEST_PACKET
{
    uint32 clientRequestId = 1;
}

message CS_CHEAT_COMMAND_PACKET
{
    CheatCommandType commandType = 1;
    uint32 requestId = 2;
}

/* ------------------------------ [ Server -> Client ]  ------------------------------ */

message SC_TIME_SYNC_PACKET
{
	uint32 probeSeq = 1;
	uint32 serverSendTimeMs = 2;
	uint64 serverFrame = 3;
}

message SC_LOGIN_SUCCESS_PACKET
{
	uint64 netid = 1;
}

message SC_LOGIN_FAIL_PACKET
{
	uint32 reason = 1;
}

message SC_ADD_PACKET
{
	uint64 netid = 1;
	uint32 typeid = 2;
	float x = 3;
	float y = 4;
	float z = 5;
	float yaw = 6;
}

message SC_MOVE_PACKET
{
	uint64 netid = 1;
	float x = 2;
	float y = 3;
	float z = 4;
	float yaw = 5;
}

message SC_REMOVE_PACKET
{
	uint64 netid = 1;
}

message SC_COMBAT_IMPACT_PACKET
{
	uint64 attackerNetId = 1;
	uint64 victimNetId = 2;
	uint32 resultType = 3;

	float impactX = 4;
	float impactY = 5;
	float impactZ = 6;

	float dirX = 7;
	float dirY = 8;
	float dirZ = 9;
}

message SC_ANIMATION_TRANSITION_PACKET
{
	uint64 netid = 1;
    int32 currAnim = 2;

	uint32 abilityInstanceId = 3;
	float normalizedTime = 4;
}

message SC_STAT_CHANGE_PACKET
{
	uint64 netid = 1;
	uint32 curhp = 2;
	uint32 maxhp = 3;
	uint32 curstamina = 4;
	uint32 maxstamina = 5;
	uint32 power = 6;
	float attackspeed = 7;
	uint32 defense = 8;
	float movespeed = 9;
}

message SC_WORLD_TRANSITION_BEGIN_PACKET
{
	uint64 transferId = 1;
    uint32 requestId = 2;

    uint32 sourceWorldDefId = 3;
    uint64 sourceWorldId = 4;

    uint32 targetWorldDefId = 5;
    uint64 targetWorldId = 6;

    uint32 mapResourceId = 7;
    uint64 playerNetId = 8;

    bool clearExistingObjects = 9;
    bool waitClientReady = 10;
    bool usedFallback = 11;

    uint32 reason = 12;
}

message SC_WORLD_TRANSITION_REJECTED_PACKET
{
	uint32 requestId = 1;
	uint32 reason = 2;
}

message SC_PARTY_UI_BOOTSTRAP_PACKET
{
	uint32 clientRequestId = 1;
	bool hasMyParty = 2;
	PartySnapshot myParty = 3;
	repeated PartyListEntry parties = 4;
}

message SC_PARTY_LIST_SNAPSHOT_PACKET
{
	uint32 clientRequestId = 1;
	repeated PartyListEntry parties = 2;
}

message SC_PARTY_COMMAND_RESULT_PACKET
{
	uint32 clientRequestId = 1;
	bool success = 2;
	uint32 error = 3;
	uint64 partyId = 4;
	uint64 joinRequestId = 5;
}

message SC_PARTY_SNAPSHOT_PACKET
{
	PartySnapshot party = 1;
}

message SC_PARTY_JOIN_REQUEST_RECEIVED_PACKET
{
	uint64 partyId = 1;
	PartyJoinRequest request = 2;
}

message SC_PARTY_JOIN_REQUEST_CLOSED_PACKET
{
	uint64 partyId = 1;
	uint64 joinRequestId = 2;
	PartyJoinRequestCloseReason reason = 3;
	PartyJoinRequestState state = 4;
}

message SC_ITEM_COUNT_PACKET
{
	uint32 hpPotionCount = 1;
}

message SC_TEAM_DEATH_COUNT_PACKET
{
	uint32 maxDeathCount = 1;
	uint32 deathCount = 2;
}

message SC_MONSTER_COMBAT_STATE_PACKET
{
	uint64 netid = 1;
	bool inCombat = 2;
}

message SC_BOSS_GIMMICK_STATE_PACKET
{
    uint64 bossNetId = 1;

    uint32 gimmickSeq = 2;

    BossGimmickType gimmickType = 3;
    BossGimmickStage stage = 4;

    float durationSec = 5;
    float remainingSec = 6;
}

message SC_BOSS_GIMMICK_OBJECT_SYNC_PACKET
{
    uint64 bossNetId = 1;

    uint32 gimmickSeq = 2;

    uint64 objectNetId = 3;
    BossGimmickObjectState state = 4;

    float x = 5;
    float y = 6;
    float z = 7;

	float radius = 8;

    uint32 curHp = 9;
    uint32 maxHp = 10;

	// uint64 assignedPlayerNetId = 5;
    uint64 brokenByPlayerNetId = 11;
}

message SC_BOSS_GIMMICK_ZONE_SYNC_PACKET
{
	uint64 bossNetId = 1;

    uint32 gimmickSeq = 2;

    uint64 zoneNetId = 3;
    BossGimmickObjectState state = 4;

    float x = 5;
    float y = 6;
    float z = 7;

    float radius = 8;
}

message SC_STAT_UI_BOOTSTRAP_PACKET
{
	uint32 clientRequestId = 1;
	repeated uint32 ownedTitleIds = 2;
	uint32 equippedTitleId = 3;
}

message SC_TITLE_EQUIP_RESULT_PACKET
{
	uint32 clientRequestId = 1;
	bool success = 2;
	uint32 equippedTitleId = 3;
	uint32 reason = 4;
}

message SC_FINAL_CLEAR_CHOICE_BEGIN_PACKET 
{
	uint64 voteId            = 1; 
	uint64 partyId           = 2;
	uint64 sourceWorldId     = 3;  
	uint32 eligibleCount     = 4;
}

message SC_FINAL_CLEAR_CHOICE_RESULT_PACKET 
{
	uint64 voteId = 1;
	FinalClearChoiceOutcome outcome = 2;
	FinalClearChoiceReason  reason  = 3;
	uint32 targetWorldDefId = 4;  
	uint64 pvpChooserNetId = 5;
}

message SC_TITLE_REPLICATION_PACKET
{
	uint64 ownerNetId = 1;
	uint32 titleId = 2;
}

message SC_PVP_ROUND_RESULT_PACKET
{
	uint64 winnerNetId = 1;
}

message SC_GAMEPLAY_EFFECT_SYNC_PACKET
{
	uint64 netid = 1;
	uint64 revision = 2;
	repeated GameplayEffectSyncEntry activeEffects = 3;
	repeated GameplayEffectSyncEntry appliedEffects = 4;
}

message SC_BEACON_CINEMATIC_START_PACKET
{
    uint64 cinematicInstanceId = 1;
    uint32 clientRequestId = 2;
    uint64 partyId = 3;
    uint64 sourceWorldId = 4;
    BeaconCinematicType cinematicType = 5;
    uint64 initiatorNetId = 6;
}