#pragma once

#include "types.h"

enum class AnimationId : uint8 {
	None,

	Knight_Idle,
	Knight_Walk,
	Knight_Run,
	Knight_LightAttack1,
	//Knight_LightAttack2,
	//Knight_LightAttack3,
	//Knight_HeavyAttack,
	//Knight_SpecialAttack,
	Knight_Dodge,
	Knight_Parry,
	Knight_Stun,
	Knight_Hit,
	Knight_Guard,
	Knight_Drinking,
	Knight_Death,

	FinalBoss_Idle,
	FinalBoss_Walk,
	FinalBoss_Thrust,
	FinalBoss_Slash,
	FinalBoss_DashSlash,
	FinalBoss_JumpSlash,
	FinalBoss_MultiSlash,
	FinalBoss_Stun,
	FinalBoss_Hit,
	FinalBoss_Death,

	Imp_Idle_1,
	Imp_Idle_2,
	Imp_Idle_3,
	Imp_Idle_4,
	Imp_Idle_5,
	Imp_Idle_6,
	Imp_Idle_Battlecry,
	Imp_Idle_Roaring,
	Imp_Melee_1,
	Imp_Melee_2,
	Imp_Melee_3,
	Imp_Melee_4,
	Imp_Melee_5,
	Imp_Walk_Back,
	Imp_Walk_Forward,
	Imp_Walk_Left,
	Imp_Walk_Right,
	Imp_Jump_1,
	Imp_Stun,
	Imp_React_Front,
	Imp_React_Left,
	Imp_React_Right,
	Imp_Death_1,
	Imp_Death_2,

	DemonStriker_Idle_1,
	DemonStriker_Idle_2,
	DemonStriker_Idle_3,
	DemonStriker_Idle_4,
	DemonStriker_Idle_5,
	DemonStriker_Idle_6_Block,
	DemonStriker_Melee_1,
	DemonStriker_Melee_2,
	DemonStriker_Melee_3,
	DemonStriker_Melee_4,
	DemonStriker_Gun_Shoot_1,
	DemonStriker_Gun_Shoot_2,
	DemonStriker_Gun_Shoot_3,
	DemonStriker_Gun_Shoot_4,
	DemonStriker_Walking_1,
	DemonStriker_Walking_2,
	DemonStriker_Walking_3,
	DemonStriker_Walking_4_Gun,
	DemonStriker_Walking_5_Gun,
	DemonStriker_Walking_6_Block,
	DemonStriker_Walking_Back,
	DemonStriker_Walking_Left,
	DemonStriker_Walking_Right,
	DemonStriker_Turn_Left,
	DemonStriker_Turn_Right,
	DemonStriker_Running_1,
	DemonStriker_Running_2,
	DemonStriker_Jump_1,
	DemonStriker_Jump_2,
	DemonStriker_Stun,
	DemonStriker_React_1_Block,
	DemonStriker_React_2_HeadShot,
	DemonStriker_React_3_Left,
	DemonStriker_React_4_Right,
	DemonStriker_Death_1,
	DemonStriker_Death_2,

	DemonExecutioner_Idle_1,
	DemonExecutioner_Idle_2,
	DemonExecutioner_Idle_3,
	DemonExecutioner_Idle_4,
	DemonExecutioner_Roar_1,
	DemonExecutioner_Roar_2,
	DemonExecutioner_Melee_1,
	DemonExecutioner_Melee_2,
	DemonExecutioner_Melee_3,
	DemonExecutioner_Melee_4,
	DemonExecutioner_Melee_5,
	DemonExecutioner_Melee_6,
	DemonExecutioner_Walk_Forward,
	DemonExecutioner_Walk_Forward_Slow,
	DemonExecutioner_Walk_Left,
	DemonExecutioner_Walk_Right,
	DemonExecutioner_Walk_Back,
	DemonExecutioner_Run,
	DemonExecutioner_Jump_1,
	DemonExecutioner_Jump_2,
	DemonExecutioner_Stun,
	DemonExecutioner_Charge,
	DemonExecutioner_Block_1,
	DemonExecutioner_Block_2,
	DemonExecutioner_GetHit_1,
	DemonExecutioner_GetHit_2,
	DemonExecutioner_GetHit_3,
	DemonExecutioner_Death,

	BigDemonWarrior_Idle_1,
	BigDemonWarrior_Idle_2,
	BigDemonWarrior_Idle_3,
	BigDemonWarrior_Idle_4,
	BigDemonWarrior_BattleCry,
	BigDemonWarrior_Roaring,
	BigDemonWarrior_Melee_1,
	BigDemonWarrior_Melee_2,
	BigDemonWarrior_Melee_3,
	BigDemonWarrior_Melee_4,
	BigDemonWarrior_Melee_5,
	BigDemonWarrior_Melee_6,
	BigDemonWarrior_Melee_7,
	BigDemonWarrior_Melee_8,
	BigDemonWarrior_WalkBack,
	BigDemonWarrior_WalkForward,
	BigDemonWarrior_WalkLeft,
	BigDemonWarrior_WalkRight,
	BigDemonWarrior_RunForward,
	BigDemonWarrior_TurnLeft,
	BigDemonWarrior_TurnRight,
	BigDemonWarrior_Jump,
	BigDemonWarrior_Stun,
	BigDemonWarrior_ReactFromLeft,
	BigDemonWarrior_ReactFromRight,
	BigDemonWarrior_ReactGut,
	BigDemonWarrior_Death,

	Tank_Idle_1,
	Tank_Idle_2,
	Tank_Idle_3,
	Tank_Idle_4,
	Tank_Idle_5,
	Tank_Melee_1,
	Tank_Melee_2,
	Tank_Melee_3,
	Tank_Melee_4,
	Tank_Melee_5,
	Tank_Melee_6,
	Tank_Melee_7,
	Tank_Melee_8,
	Tank_Walk_1,
	Tank_Walk_2,
	Tank_WalkBack,
	Tank_WalkLeftBack,
	Tank_WalkLeft,
	Tank_WalkRightBack,
	Tank_WalkRight,
	Tank_TurnLeft,
	Tank_TurnRight,
	Tank_Running1,
	Tank_Running2,
	Tank_Jump1,
	Tank_Jump2,
	Tank_Stun,
	Tank_Death1,
	Tank_Death2,
};

inline uint32 ToInt(AnimationId type) { return static_cast<uint32>(type); }

namespace std {
	template<>
	struct hash<AnimationId> {
		size_t operator()(const AnimationId& type) const noexcept
		{
			return std::hash<uint32>()(ToInt(type));
		}
	};
}
