#pragma once

#include "types.h"

enum class PacketType : uint8 {
	CS_LOGIN,
	CS_CHARACTER_SELECT,
	CS_MOVE,
	CS_ATTACK,
	CS_DODGE,
	CS_GUARD,
	CS_PARRY,
	CS_USE_ITEM,
	CS_WORLD_TRANSITION_REQUEST,
	CS_WORLD_TRANSITION_READY,

	SC_LOGIN_SUCCESS,
	SC_LOGIN_FAIL,
	SC_MOVE_OBJECT,
	SC_ADD,
	SC_REMOVE,
	SC_COMBAT_IMPACT,
	SC_ANIMATION_CHANGE,
	SC_STAT_CHANGE,
	SC_WORLD_TRANSITION_BEGIN,
	SC_WORLD_TRANSITION_REJECTED,

	SC_REPLICATION_FRAME,
};
